---
title: "Testing"
author: "Victor M. Uribe"
date: "2022-08-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(psych)
```




```{r}
# Get the Data

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load('2022-08-16')
tuesdata <- tidytuesdayR::tt_load(2022, week = 33)

characters <- tuesdata$characters

# Or read in the data manually

characters <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-08-16/characters.csv')

```



```{r}
str(characters)
```

```{r}
infj_dist <- tuesdata$myers_briggs %>%
  filter(myers_briggs == "INFJ") %>%
  ggplot(aes(myers_briggs)) + geom_bar() + facet_wrap(~uni_name)

infj_dist

#unique(tuesdata$myers_briggs$myers_briggs)

```

















